// --- State Management with Undo/Redo & Persistence ---

const STORAGE_KEY = 'niras_vent_current_project';

/**
 * Intern hjælpefunktion til Auto-healing af grafen ved sletning.
 * Den er flyttet direkte ind i app_state for at undgå import-crashes.
 */
function generateSmartTransition(parentComp, newComp) {
    if (!parentComp || !newComp) return null;

    const shapeIn = parentComp.shapeOut || parentComp.shape || 'circular';
    const dIn = parseFloat(parentComp.diameterOut || parentComp.diameter || 0);
    const wIn = parseFloat(parentComp.widthOut || parentComp.width || 0);
    const hIn = parseFloat(parentComp.heightOut || parentComp.height || 0);

    const shapeOut = newComp.shapeIn || newComp.shape || 'circular';
    const dOut = parseFloat(newComp.diameterIn || newComp.diameter || 0);
    const wOut = parseFloat(newComp.widthIn || newComp.width || 0);
    const hOut = parseFloat(newComp.heightIn || newComp.height || 0);

    if (shapeIn === shapeOut && dIn === dOut && wIn === wOut && hIn === hOut) {
        return null; 
    }

    const areaIn = shapeIn === 'circular' ? Math.PI * Math.pow(dIn / 2, 2) : (wIn * hIn);
    const areaOut = shapeOut === 'circular' ? Math.PI * Math.pow(dOut / 2, 2) : (wOut * hOut);

    const tolerance = areaIn * 0.01; 
    let fittingType = 'transition';
    let name = 'Overgang';

    if (areaOut > (areaIn + tolerance)) {
        fittingType = 'expansion';
        name = `Udvidelse (${shapeIn === 'circular' ? 'Ø'+dIn : wIn+'x'+hIn} -> ${shapeOut === 'circular' ? 'Ø'+dOut : wOut+'x'+hOut})`;
    } else if (areaOut < (areaIn - tolerance)) {
        fittingType = 'contraction';
        name = `Indsnævring (${shapeIn === 'circular' ? 'Ø'+dIn : wIn+'x'+hIn} -> ${shapeOut === 'circular' ? 'Ø'+dOut : wOut+'x'+hOut})`;
    } else if (shapeIn !== shapeOut) {
        fittingType = 'transition'; 
        name = `Formovergang (${shapeIn} -> ${shapeOut})`;
    }

    return {
        id: `trans_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
        name: name,
        type: 'fitting',
        fittingType: fittingType,
        shape: shapeIn,
        diameter: dIn,
        width: wIn,
        height: hIn,
        shapeOut: shapeOut,
        diameterOut: dOut,
        widthOut: wOut,
        heightOut: hOut,
        length: 500, 
        isIncluded: true,
        isAutoGenerated: true
    };
}


class StateManager {
    constructor() {
        this.historyPaused = false; // NYT: Lås der forhindrer spam i historikken
        this.resetState();
        this.history = [];
        this.future = [];
        this.maxHistory = 50;

        // Try to load from local storage on init
        this.loadFromStorage();
    }

    // Funktioner til at styre historik-låsen
    pauseHistory() { this.historyPaused = true; }
    resumeHistory() { this.historyPaused = false; }

    resetState() {
        this.state = {
            fittingsList: [],
            systemComponents: [], // Deprecated, but kept for UI compat temporarily during transition
            graph: {
                nodes: {}, // id -> component object
                edges: [], // { from: id, fromPort: 'outlet', to: id, toPort: 'inlet' }
            },
            ductResult: null,
            correctionTargetId: null,
            projectName: '',
            startAirflow: '1000',
            systemType: 'splitting',
            temperature: '20'
        };
    }

    importState(importedState) {
        this.resetState();
        if (!importedState) return;

        // Merge properties
        Object.assign(this.state, importedState);

        // Ensure graph structure exists (Backwards Compatibility for Pre-Phase-12 projects)
        if (!this.state.graph || !this.state.graph.nodes) {
            this.setSystemComponents(this.state.systemComponents || []);
        }

        this.history = [];
        this.future = [];
        this.persist();
        this.notifyChange();
    }

    // --- History Management ---

    saveState(actionDescription = 'State Change') {
        if (this.historyPaused) return; // Afviser snapshots, hvis vi er midt i en beregnings-loop!

        const stateClone = JSON.parse(JSON.stringify(this.state));
        this.history.push({ state: stateClone, description: actionDescription });
        if (this.history.length > this.maxHistory) this.history.shift();

        // Clear future on new action
        this.future = [];

        this.persist();
        this.notifyChange();
    }

    undo() {
        if (this.history.length === 0) return false;

        const currentState = JSON.parse(JSON.stringify(this.state));
        this.future.push(currentState);

        const previousEntry = this.history.pop();
        this.state = previousEntry.state;

        this.persist();
        this.notifyChange();
        return true;
    }

    redo() {
        if (this.future.length === 0) return false;

        const currentState = JSON.parse(JSON.stringify(this.state));
        this.saveToHistoryStack(currentState); // Move current to history without clearing future

        const nextState = this.future.pop();
        this.state = nextState;

        this.persist();
        this.notifyChange();
        return true;
    }

    // Helper to push to history without clearing future (used by redo)
    saveToHistoryStack(state) {
        this.history.push({ state: state, description: 'Redo' });
        if (this.history.length > this.maxHistory) this.history.shift();
    }

    // --- Persistence ---

    persist() {
        try {
            localStorage.setItem(STORAGE_KEY, JSON.stringify(this.state));
            console.log('State saved:', this.state);
        } catch (e) {
            console.error("Failed to save to localStorage", e);
        }
    }

    loadFromStorage() {
        try {
            const stored = localStorage.getItem(STORAGE_KEY);
            if (stored) {
                this.state = JSON.parse(stored);
                console.log('State loaded:', this.state);
            } else {
                console.log('No state found in localStorage');
            }
        } catch (e) {
            console.error("Failed to load from localStorage", e);
        }
    }

    // --- State Accessors & Mutators (Delegates) ---

    // Fittings
    getFittings() { return this.state.fittingsList; }
    addFitting(fitting) {
        this.saveState(`Added fitting ${fitting.name}`);
        this.state.fittingsList.push(fitting);
        this.persist();
    }
    removeFitting(id) {
        this.saveState(`Removed fitting ${id}`);
        this.state.fittingsList = this.state.fittingsList.filter(f => f.id !== id);
        // Remove paired components logic (e.g. Tee parts)
        if (this.state.fittingsList.find(f => f.id === id + 1 || f.id === id - 1)) {
            this.state.fittingsList = this.state.fittingsList.filter(f => f.id !== id + 1 && f.id !== id - 1);
        }
        this.persist();
    }
    resetFittings() {
        this.saveState('Reset fittings');
        this.state.fittingsList = [];
        this.persist();
    }

    // --- Graph-Based System Components ---
    getGraph() {
        if (!this.state.graph) {
            this.state.graph = { nodes: {}, edges: [] };
        }
        return this.state.graph;
    }

    addSystemComponent(comp, parentId = null, parentPort = 'outlet', targetPort = 'inlet') {
        if (!comp) {
            console.error('StateManager: addSystemComponent called with null component');
            return;
        }

        console.log('StateManager: addSystemComponent (Graph) called', comp.name, 'parentId:', parentId);
        this.saveState(`Added component ${comp.name}`);

        // Default to included in calculation
        if (comp.isIncluded === undefined) {
            comp.isIncluded = true;
        }

        const graph = this.getGraph();

        // Add the new node
        graph.nodes[comp.id] = comp;

        // Only create an edge if parentId is given AND it exists
        if (parentId && graph.nodes[parentId]) {
            graph.edges.push({
                from: parentId,
                fromPort: parentPort,
                to: comp.id,
                toPort: targetPort
            });
        }

        // Backward compatibility sync
        this.syncGraphToArray();
        this.persist();
    }

    // NYT: Hjælpefunktion til at slette et helt undertræ af komponenter
    deleteSubTree(startNodeId) {
        const graph = this.getGraph();
        const toDelete = [startNodeId];
        let i = 0;
        
        // Find alle descendants iterativt
        while (i < toDelete.length) {
            const current = toDelete[i];
            const outEdges = graph.edges.filter(e => e.from === current);
            outEdges.forEach(e => {
                if (!toDelete.includes(e.to)) toDelete.push(e.to);
            });
            i++;
        }

        // Slet dem alle fra grafen
        toDelete.forEach(id => {
            delete graph.nodes[id];
            graph.edges = graph.edges.filter(e => e.from !== id && e.to !== id);
        });
        
        console.log(`[Graf-Healing] Slettede afkoblet gren med ${toDelete.length} komponenter.`);
    }

    removeSystemComponent(id, keptEdgeIndex = null) {
        const graph = this.getGraph();
        const nodeToDelete = graph.nodes[id];
        
        if (!nodeToDelete) return;

        // 1. Find forbindelser FØR vi sletter noget
        const incomingEdges = graph.edges.filter(e => e.to === id);
        const outgoingEdges = graph.edges.filter(e => e.from === id);

        let outEdgeToKeep = null;
        let branchesToDelete = [];

        // 2. T-stykke Håndtering: UI'et har allerede spurgt brugeren via custom modal
        // og sendt deres valg hertil via 'keptEdgeIndex'
        if (incomingEdges.length === 1 && outgoingEdges.length > 1) {
            if (keptEdgeIndex !== null && keptEdgeIndex >= 0 && keptEdgeIndex < outgoingEdges.length) {
                outEdgeToKeep = outgoingEdges[keptEdgeIndex];
                branchesToDelete = outgoingEdges.filter((e, i) => i !== keptEdgeIndex).map(e => e.to);
            } else {
                // Fallback hvis UI af en eller anden grund fejler: Slet alle tilsluttede grene
                branchesToDelete = outgoingEdges.map(e => e.to);
            }
        } else if (incomingEdges.length === 1 && outgoingEdges.length === 1) {
            // Standard ligeud healing
            outEdgeToKeep = outgoingEdges[0];
        }

        // --- OK, brugeren har svaret / det var simpelt. Nu starter sletningen ---
        this.saveState(`Removed component ${id}`);

        // 3. Slet uønskede grene (undgå 'svævende' rør)
        branchesToDelete.forEach(branchStartId => {
            if (typeof this.deleteSubTree === 'function') {
                this.deleteSubTree(branchStartId);
            }
        });

        // 4. Fjern selve komponenten og dens ind/ud forbindelser
        delete graph.nodes[id];
        graph.edges = graph.edges.filter(e => e.from !== id && e.to !== id);

        // 5. --- GRAF HEALING & AUTO-OVERGANG ---
        if (incomingEdges.length === 1 && outEdgeToKeep) {
            const inEdge = incomingEdges[0];
            const pNode = graph.nodes[inEdge.from];
            const cNode = graph.nodes[outEdgeToKeep.to];

            let autoTransition = null;

            // Undersøg om der er et dimension-mismatch der kræver en overgang
            if (pNode && cNode && pNode.state && cNode.state) {
                const pDim = pNode.state.outletDimension ? (pNode.state.outletDimension[inEdge.fromPort] || pNode.state.outletDimension['outlet']) : null;
                const cDim = cNode.state.inletDimension;

                if (pDim && cDim) {
                    const mockParent = { shapeOut: pDim.shape === 'rect' ? 'rectangular' : 'circular', diameterOut: pDim.d, widthOut: pDim.w, heightOut: pDim.h };
                    const mockChild = { shapeIn: cDim.shape === 'rect' ? 'rectangular' : 'circular', diameterIn: cDim.d, widthIn: cDim.w, heightIn: cDim.h };
                    if (typeof generateSmartTransition === 'function') {
                        autoTransition = generateSmartTransition(mockParent, mockChild);
                    }
                }
            }

            // Gennemfør "Sammensyningen"
            if (autoTransition) {
                console.log(`[Graf-Healing] Dimensioner afveg. Indsætter auto-overgang: ${autoTransition.name}`);
                graph.nodes[autoTransition.id] = autoTransition;
                
                // Mor -> Overgang
                graph.edges.push({
                    from: inEdge.from,
                    fromPort: inEdge.fromPort,
                    to: autoTransition.id,
                    toPort: 'inlet'
                });
                
                // Overgang -> Barn
                graph.edges.push({
                    from: autoTransition.id,
                    fromPort: 'outlet',
                    to: outEdgeToKeep.to,
                    toPort: outEdgeToKeep.toPort
                });
            } else {
                console.log(`[Graf-Healing] Direkte match! Forbandt automatisk ${inEdge.from} med ${outEdgeToKeep.to}`);
                graph.edges.push({
                    from: inEdge.from,
                    fromPort: inEdge.fromPort,
                    to: outEdgeToKeep.to,
                    toPort: outEdgeToKeep.toPort
                });
            }
        }

        this.syncGraphToArray();
        this.persist();
    }

    removeLastSystemComponent() {
        this.saveState('Removed last component');
        const graph = this.getGraph();
        const nodeIds = Object.keys(graph.nodes);
        if (nodeIds.length === 0) return;

        // Find a leaf node (no outgoing edges)
        const leafId = nodeIds.reverse().find(id => !graph.edges.find(e => e.from === id));
        if (leafId) {
            delete graph.nodes[leafId];
            graph.edges = graph.edges.filter(e => e.from !== leafId && e.to !== leafId);
        } else {
            // Fallback if no leaf found (e.g. cycle, which shouldn't happen)
            const lastId = nodeIds[nodeIds.length - 1];
            delete graph.nodes[lastId];
            graph.edges = graph.edges.filter(e => e.from !== lastId && e.to !== lastId);
        }

        this.syncGraphToArray();
        this.persist();
    }

    clearSystem() {
        this.saveState('Cleared system');
        this.state.graph = { nodes: {}, edges: [] };
        this.state.systemComponents = [];
        this.state.correctionTargetId = null;
        this.persist();
    }

    getSystemComponent(id) {
        return this.getGraph().nodes[id] || this.state.systemComponents.find(c => c.id === id);
    }

    updateSystemComponent(id, newData) {
        this.saveState(`Updated component ${newData.name}`);
        const graph = this.getGraph();
        if (graph.nodes[id]) {
            graph.nodes[id] = { ...graph.nodes[id], ...newData };
            this.syncGraphToArray();
            this.persist();
        } else {
            // Fallback for array
            const index = this.state.systemComponents.findIndex(c => c.id === id);
            if (index !== -1) {
                this.state.systemComponents[index] = { ...this.state.systemComponents[index], ...newData };
                this.persist();
            }
        }
    }

    // Temporary helper to keep the array synced for UI rendering until UI is fully graph-aware
    syncGraphToArray() {
        const graph = this.getGraph();
        const nodes = graph.nodes;
        const edges = graph.edges;

        let ordered = [];
        const visited = new Set();

        const traverse = (nodeId) => {
            if (!visited.has(nodeId) && nodes[nodeId]) {
                visited.add(nodeId);
                ordered.push(nodes[nodeId]);

                // Follow all outgoing edges
                const outgoingEdges = edges.filter(e => e.from === nodeId);
                // Prefer main 'outlet' first
                outgoingEdges.sort((a, b) => a.fromPort === 'outlet' ? -1 : 1).forEach(e => {
                    traverse(e.to);
                });
            }
        };

        // Find root nodes (no incoming edges)
        const rootNodes = Object.keys(nodes).filter(id => !edges.find(e => e.to === id));
        rootNodes.forEach(id => traverse(id));

        // Add any remaining disconnected stranded nodes
        for (const id in nodes) {
            if (!visited.has(id)) {
                traverse(id);
            }
        }

        this.state.systemComponents = ordered;
    }

    // Build a nested tree representation of the graph
    getSystemTree() {
        const graph = this.getGraph();
        const nodes = graph.nodes;
        const edges = graph.edges;
        const visited = new Set();

        const buildTree = (nodeId) => {
            if (visited.has(nodeId)) return null; // Avoid cycles
            const node = nodes[nodeId];
            if (!node) return null;

            visited.add(nodeId);
            const treeNode = { ...node, children: {} };

            // Find all outgoing edges from this node
            const outgoingEdges = edges.filter(e => e.from === nodeId);

            // For each edge, attach the child to the corresponding port
            outgoingEdges.forEach(edge => {
                const childTree = buildTree(edge.to);
                if (childTree) {
                    if (!treeNode.children[edge.fromPort]) {
                        treeNode.children[edge.fromPort] = [];
                    }
                    treeNode.children[edge.fromPort].push(childTree);
                }
            });

            return treeNode;
        };

        // Find root nodes (no incoming edges)
        const roots = Object.keys(nodes).filter(id => !edges.find(e => e.to === id));
        let treeRoots = roots.map(rootId => buildTree(rootId)).filter(Boolean);

        // Append any stranded nodes that were not reached as additional roots
        for (const id in nodes) {
            if (!visited.has(id)) {
                let strandedTree = buildTree(id);
                if (strandedTree) treeRoots.push(strandedTree);
            }
        }

        return treeRoots;
    }

    // System Components (Legacy array accessors) - keeping interface identical to not break UI instantly
    getSystemComponents() {
        if (!this.state.graph) this.state.graph = { nodes: {}, edges: [] };
        if (Object.keys(this.state.graph.nodes).length > 0 && this.state.systemComponents.length === 0) {
            this.syncGraphToArray();
        }
        return this.state.systemComponents;
    }

    setSystemComponents(comps) {
        this.saveState('Set system components');
        // Rebuild graph from array sequence
        this.state.graph = { nodes: {}, edges: [] };
        comps.forEach((c, index) => {
            this.state.graph.nodes[c.id] = c;
            if (index > 0) {
                this.state.graph.edges.push({
                    from: comps[index - 1].id,
                    fromPort: 'outlet',
                    to: c.id,
                    toPort: 'inlet'
                });
            }
        });
        this.state.systemComponents = comps;
        this.persist();
    }

    // Duct Result
    getDuctResult() { return this.state.ductResult; }
    setDuctResult(res) {
        // We typically don't undo/redo calculation results unless they impact global state?
        // Let's not save history for this temporary calculation result, but stick it in state.
        this.state.ductResult = res;
        // No persist needed for transient calculation result? Or maybe yes if we want to restore exact screen.
        // For now, let's keep it transient.
    }

    // Correction Target
    getCorrectionTargetId() { return this.state.correctionTargetId; }
    setCorrectionTargetId(id) {
        this.state.correctionTargetId = id;
        // No history save for UI selection state change? Or yes?
        // Usually selection changes shouldn't trigger undo stack pushes.
    }

    // Project Meta (New)
    setProjectParams(params) {
        // params: { projectName, startAirflow, systemType, temperature }
        // We only save history if meaningful change? 
        // For inputs, we might not want to save on every keypress. 
        // Let's assume this is called on specific actions or blur.
        Object.assign(this.state, params);
        this.persist();
    }

    notifyChange() {
        // Dispatch custom event for UI updates if needed
        window.dispatchEvent(new CustomEvent('stateChanged', { detail: this.state }));
    }
}

// Singleton Instance
export const stateManager = new StateManager();

// --- Exported Wrappers (Backward Compatibility) ---

export function getFittings() { return stateManager.getFittings(); }
export function addFitting(fitting) { stateManager.addFitting(fitting); }
export function removeFitting(id) { stateManager.removeFitting(id); }
export function resetFittings() { stateManager.resetFittings(); }

export function getSystemComponents() { return stateManager.getSystemComponents(); }
export function addSystemComponent(comp) {
    console.log('Wrapper: addSystemComponent called', comp);
    stateManager.addSystemComponent(comp);
}
export function removeLastSystemComponent() { stateManager.removeLastSystemComponent(); }
export function clearSystem() { stateManager.clearSystem(); }
export function setSystemComponents(comps) { stateManager.setSystemComponents(comps); }
export function getSystemComponent(id) { return stateManager.getSystemComponent(id); }
export function updateSystemComponent(id, newData) { stateManager.updateSystemComponent(id, newData); }
export function deleteSystemComponent(id, keptEdgeIndex = null) { stateManager.removeSystemComponent(id, keptEdgeIndex); }

export function getDuctResult() { return stateManager.getDuctResult(); }
export function setDuctResult(res) { stateManager.setDuctResult(res); }

export function getCorrectionTargetId() { return stateManager.getCorrectionTargetId(); }
export function setCorrectionTargetId(id) { stateManager.setCorrectionTargetId(id); }

// --- New Undo/Redo Exports ---
export const undo = () => stateManager.undo();
export const redo = () => stateManager.redo();
export const canUndo = () => stateManager.history.length > 0;
export const canRedo = () => stateManager.future.length > 0;

// Eksportér funktionerne til hovedfilen
export const pauseHistory = () => stateManager.pauseHistory();
export const resumeHistory = () => stateManager.resumeHistory();