/**
 * Parses a string with potentially comma decimal separator to a float.
 * @param {string|number} str 
 * @returns {number}
 */
export function parseLocalFloat(str) {
    return parseFloat(String(str).replace(",", "."));
}

/**
 * Formats a number with comma decimal separator.
 * @param {number} num 
 * @param {number} decimals 
 * @returns {string}
 */
export function formatLocalFloat(num, decimals) {
    return num.toFixed(decimals).replace(".", ",");
}

/**
 * Gets internal dimension by subtracting wall thickness.
 * @param {number} ext_mm 
 * @param {number} wallThickness 
 * @returns {number}
 */
export function getInternalDim(ext_mm, wallThickness = 0.5) {
    return Math.max(0, ext_mm - 2 * wallThickness);
}

/**
 * Genererer en fysisk korrekt overgang (indsnævring/udvidelse/formskift) 
 * baseret på tværsnitsarealerne mellem to komponenter.
 * * @param {Object} parentComp - Den eksisterende komponent (Inlet til overgangen)
 * @param {Object} newComp - Den komponent brugeren forsøger at tilføje (Outlet fra overgangen)
 * @returns {Object|null} - Returnerer overgangs-komponenten, eller null hvis de er identiske.
 */
export function generateSmartTransition(parentComp, newComp) {
    if (!parentComp || !newComp) return null;

    // 1. Aflæs dimensioner fra forælderen (hvad forlader luften?)
    const shapeIn = parentComp.shapeOut || parentComp.shape || 'circular';
    const dIn = parseFloat(parentComp.diameterOut || parentComp.diameter || 0);
    const wIn = parseFloat(parentComp.widthOut || parentComp.width || 0);
    const hIn = parseFloat(parentComp.heightOut || parentComp.height || 0);

    // 2. Aflæs dimensioner fra barnet (hvad træder luften ind i?)
    const shapeOut = newComp.shapeIn || newComp.shape || 'circular';
    const dOut = parseFloat(newComp.diameterIn || newComp.diameter || 0);
    const wOut = parseFloat(newComp.widthIn || newComp.width || 0);
    const hOut = parseFloat(newComp.heightIn || newComp.height || 0);

    // 3. Hvis de er 100% identiske, behøver vi ingen overgang
    if (shapeIn === shapeOut && dIn === dOut && wIn === wOut && hIn === hOut) {
        return null; 
    }

    // 4. Beregn arealer i mm² for præcis sammenligning
    const areaIn = shapeIn === 'circular' ? Math.PI * Math.pow(dIn / 2, 2) : (wIn * hIn);
    const areaOut = shapeOut === 'circular' ? Math.PI * Math.pow(dOut / 2, 2) : (wOut * hOut);

    // Tolerance på 1% for afrundingsfejl ved konverteringer
    const tolerance = areaIn * 0.01; 
    let fittingType = 'transition';
    let name = 'Overgang';

    if (areaOut > (areaIn + tolerance)) {
        fittingType = 'expansion';
        name = `Udvidelse (${shapeIn === 'circular' ? 'Ø'+dIn : wIn+'x'+hIn} -> ${shapeOut === 'circular' ? 'Ø'+dOut : wOut+'x'+hOut})`;
    } else if (areaOut < (areaIn - tolerance)) {
        fittingType = 'contraction';
        name = `Indsnævring (${shapeIn === 'circular' ? 'Ø'+dIn : wIn+'x'+hIn} -> ${shapeOut === 'circular' ? 'Ø'+dOut : wOut+'x'+hOut})`;
    } else if (shapeIn !== shapeOut) {
        fittingType = 'transition'; // Samme areal, men formskift
        name = `Formovergang (${shapeIn} -> ${shapeOut})`;
    }

    // 5. Byg og returner overgangskomponenten (Klar til physics.js)
    return {
        id: `trans_${Date.now()}_${Math.floor(Math.random() * 1000)}`, // Unikt ID
        name: name,
        type: 'fitting',
        fittingType: fittingType,
        shape: shapeIn,
        diameter: dIn,
        width: wIn,
        height: hIn,
        shapeOut: shapeOut,
        diameterOut: dOut,
        widthOut: wOut,
        heightOut: hOut,
        length: 500, // Standard branch-længde for overgange (kan gøres dynamisk senere)
        isIncluded: true,
        isAutoGenerated: true // God practice: Marker at systemet har indsat denne, ifm. UI-visning/sletning
    };
}
